/**
 * Stripe-mock helpers — used when STRIPE_SECRET is literal "PLACEHOLDER".
 *
 * Under MPP/SPT the mock replaces the whole mppx payment gate:
 *   - First pass (no `Authorization: Payment ...`) → return a 402 with a
 *     real, HMAC-bound MPP Challenge generated by mppx itself (no Stripe
 *     call). See generate.mjs mock branch.
 *   - Retry pass (any `Authorization: Payment ...`, including the literal
 *     `spt=PLACEHOLDER` the agent sends when its SPT secret is also
 *     PLACEHOLDER) → skip verify, return 200. Payment-Receipt is omitted
 *     in mock mode; the agent does not require one.
 *
 * We do not try to run mppx/server's verify() against Stripe with fake
 * keys: verify() unconditionally POSTs to api.stripe.com, which rejects
 * placeholder SPTs.
 */
import { Challenge } from 'mppx'

export function isMockSecret(value) {
  return value === 'PLACEHOLDER' || value === undefined || value === null || value === ''
}

export function mockChallengeResponse(challenge) {
  const wwwAuth = Challenge.serialize(challenge)
  const body = {
    type: 'https://paymentauth.org/problems/payment-required',
    title: 'Payment Required',
    status: 402,
    detail: 'Payment is required.',
    challengeId: challenge.id,
  }
  return {
    statusCode: 402,
    headers: {
      'Content-Type': 'application/problem+json',
      'WWW-Authenticate': wwwAuth,
      'x-amzn-remapped-www-authenticate': wwwAuth,
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Expose-Headers':
        'WWW-Authenticate,Payment-Receipt,X-Payment-Intent-Id,x-amzn-remapped-www-authenticate',
    },
    body: JSON.stringify(body),
  }
}

export function mockAccept200(body, extraHeaders = {}) {
  return {
    statusCode: 200,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Expose-Headers':
        'WWW-Authenticate,Payment-Receipt,X-Payment-Intent-Id,x-amzn-remapped-www-authenticate',
      ...extraHeaders,
    },
    body: JSON.stringify(body),
  }
}
